"""add phone number

Revision ID: 3d6571d84617
Revises: a4e262c6f9a0
Create Date: 2023-01-01 12:19:45.325535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6571d84617'
down_revision = 'a4e262c6f9a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
